name: Unity CI (Debug + Release)

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  UNITY_VERSION: 6000.2.2f1

jobs:
  # -----------------
  #  DEVELOPMENT BUILD
  # -----------------
  dev-build:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Library cache → build süresini ciddi düşürür
      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: library-${{ runner.os }}-${{ env.UNITY_VERSION }}-${{ hashFiles('ProjectSettings/ProjectVersion.txt', 'Packages/manifest.json', 'Packages/packages-lock.json') }}
          restore-keys: |
            library-${{ runner.os }}-${{ env.UNITY_VERSION }}-
            library-${{ runner.os }}-


      - name: Build (Development)
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ env.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ env.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ env.UNITY_SERIAL }}
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: StandaloneWindows64
          buildName: SpaceTrader
          buildMethod: BuildScript.BuildWindowsDevelopment
          allowDirtyBuild: true
          customParameters: -nographics -quit

      - name: Package Development Build
        if: github.event_name == 'workflow_dispatch'       # if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        run: |
          mkdir -p exports
          zip -r "exports/dev_${GITHUB_SHA}.zip" build/StandaloneWindows64 > /dev/null

      - name: Upload Dev Artifact
        if: github.event_name == 'workflow_dispatch'       # if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: dev-${{ github.sha }}
          path: exports/dev_${{ github.sha }}.zip
          if-no-files-found: error

  # -----------------
  #  RELEASE BUILD
  # -----------------
  release-build:
    # Main push veya manuel çalıştırmada dev-build sonrası çalışsın
    if: ${{ github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' }}
    needs: dev-build
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: |
            Library
          key: library-${{ runner.os }}-${{ env.UNITY_VERSION }}-${{ hashFiles('Packages/packages-lock.json') }}
          restore-keys: |
            library-${{ runner.os }}-${{ env.UNITY_VERSION }}-

      - name: Build (Release)
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ env.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ env.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ env.UNITY_SERIAL }}
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: StandaloneWindows64
          buildName: SpaceTrader
          buildMethod: BuildScript.BuildWindowsRelease
          allowDirtyBuild: true
          customParameters: -nographics -quit

      - name: Package Release Build
        run: |
          mkdir -p exports
          zip -r "exports/release_${GITHUB_SHA}.zip" build/StandaloneWindows64 > /dev/null

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ github.sha }}
          path: exports/release_${{ github.sha }}.zip
          if-no-files-found: error
