name: Unity Activation (one-time)
on: workflow_dispatch

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Request activation file (.alf)
        uses: game-ci/unity-request-activation-file@v4
        with:
          unityVersion: 6000.2.2f1
      - name: Upload .alf
        uses: actions/upload-artifact@v4
        with:
          name: Unity_ActivationFile
          path: ./*.alf
